[package]
name = "ofdb-kv"
description = "Embedded and remote key-value database facade"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "ofdb_kv"

[features]
default = []
std = []
remote = ["std", "dep:proto-kv", "dep:tonic", "dep:tokio", "dep:tower", "dep:hyper-util"]
in-memory = ["std", "dep:btree", "dep:kv-store", "dep:uuid", "btree/in-memory"]
redb = ["std", "dep:btree", "dep:kv-store", "dep:uuid", "dep:btree-redb", "dep:redb"]
server = ["remote", "dep:kv-server"]
sync = ["std", "dep:btree", "dep:kv-sync", "dep:kv-store", "dep:uuid"]

[dependencies]
# Internal dependencies
btree = { version = "0.1", path = "../btree", package = "ofdb-btree", default-features = false, features = ["std"], optional = true }
btree-redb = { version = "0.1", path = "../btree-redb", package = "ofdb-btree-redb", default-features = false, features = [], optional = true }
kv-server = { version = "0.1", path = "../kv-server", package = "ofdb-kv-server", default-features = false, features = [], optional = true }
kv-store = { version = "0.1", path = "../kv-store", package = "ofdb-kv-store", default-features = false, features = [], optional = true }
kv-sync = { version = "0.1", path = "../kv-sync", package = "ofdb-kv-sync", default-features = false, features = [], optional = true }
proto-kv = { version = "0.1", path = "../proto-kv", package = "ofdb-kv-proto", default-features = false, features = [], optional = true }

# External dependencies
hyper-util = { version = "0.1", default-features = false, features = ["tokio"], optional = true }
redb = { version = "4.3", default-features = false, features = ["uuid"], optional = true }
tokio = { version = "1.0", default-features = false, features = ["net", "time"], optional = true }
tonic = { version = "0.14", default-features = false, features = ["transport", "channel", "codegen"], optional = true }
tower = { version = "0.5", default-features = false, features = ["util"], optional = true }
uuid = { version = "1.23", default-features = false, features = ["v7", "std"], optional = true }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["executor", "std"] }
