[package]
name = "ofdb-sql-query"
description = "db query"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
name = "query"

[features]
default = ["std"]
std = [
  "uuid/std",

  "serde/std",
  "thiserror/std",
  "schema/std",
  "value/std"
]
wasm = ["dep:tsify", "dep:serde-wasm-bindgen", "dep:wasm-bindgen", "schema/wasm", "value/wasm"]

[dependencies]
# internal dependencies
value = { version = "0.1", path = "../sql-value", package = "ofdb-sql-value", default-features = false, features = [] }
schema = { version = "0.1", path = "../sql-schema", package = "ofdb-sql-schema", default-features = false, features = [] }

uuid = { version = "1.23", default-features = false, features = [] }
thiserror = { version = "2.0", default-features = false, features = [] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }

# Optional TS generation + serde for tsify
tsify = { version = "0.5", default-features = false, features = ["js"], optional = true }
serde-wasm-bindgen = { version = "0.6", default-features = false, features=[], optional = true }
wasm-bindgen = { version = "0.2", default-features = false, features = [
], optional = true }
