[package]
name = "ofdb-value"
description = "Storage value types and codecs for ofdb"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
name = "value"

[features]
default = ["std", "automerge", "redb"]
std = [
  "uuid/std",

  "serde/std",
  "serde_json/std",
  "postcard?/use-std"
]
wasm = ["dep:tsify", "dep:serde-wasm-bindgen", "dep:wasm-bindgen", "automerge/wasm"]
redb = ["dep:redb", "dep:postcard", "std"]
automerge = ["dep:automerge", "dep:autosurgeon", "std"]
serde_json = ["dep:serde_json"]

[dependencies]
uuid = { version = "1.23", default-features = false, features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"], optional = true }

# redb
redb = { version = "4.3", default-features = false, features = ["uuid"], optional = true }
postcard = { version = "1.1", default-features = false, features = ["heapless-cas"], optional = true }

# automerge
automerge = { version = "0.10", default-features = false, features = [], optional = true }
autosurgeon = { version = "0.12", default-features = false, features = ["uuid"], optional = true }

# Optional TS generation + serde for tsify
tsify = { version = "0.5", default-features = false, features = ["js"], optional = true }
serde-wasm-bindgen = { version = "0.6", default-features = false, features=[], optional = true }
wasm-bindgen = { version = "0.2", default-features = false, features = [
], optional = true }
