[package]
name = "ofdb-sql-engine"
description = "Engine layer of the database"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
name = "engine"

[features]
default = ["std"]
std = [
  "futures/std",
  "uuid/std",
  "async-lock/std",
  "serde/std",
  "serde_json/std",
  "btree/std",
  "schema/std",
  "value/std",
  "query/std"
]
in-memory = []
wasm = ["dep:tsify", "dep:serde-wasm-bindgen", "dep:wasm-bindgen", "value/wasm", "query/wasm", "schema/wasm"]

[dependencies]
# internal dependencies
btree = { version = "0.1", path = "../btree", package = "ofdb-btree", default-features = false, features = [] }
query = { version = "0.1", path = "../sql-query", package = "ofdb-sql-query", default-features = false, features = [] }
schema = { version = "0.1", path = "../sql-schema", package = "ofdb-sql-schema", default-features = false, features = [] }
value = { version = "0.1", path = "../value", package = "ofdb-value", default-features = false, features = [] }


# external dependencies
async-lock = { version = "3.4", default-features = false, features = [] }
async-stream = { version = "0.3", default-features = false, features = [] }
futures = { version = "0.3", default-features = false, features = [] }
postcard = { version = "1.1", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sha2 = { version = "0.10", default-features = false, features = [] }
thiserror = { version = "2.0", default-features = false }
uuid = { version = "1.23", default-features = false, features = ["serde", "v7"] }

# Optional TS generation + serde for tsify
tsify = { version = "0.5", default-features = false, features = ["js"], optional = true }
serde-wasm-bindgen = { version = "0.6", default-features = false, features=[], optional = true }
wasm-bindgen = { version = "0.2", default-features = false, features = [
], optional = true }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["executor"] }
