[package]
name = "ofdb-kv-server"
description = "gRPC server for ofdb KV stores"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# Internal dependencies
btree = { version = "0.1", path = "../btree", package = "ofdb-btree", default-features = false, features = ["std"] }
kv = { version = "0.1", path = "../kv-store", package = "ofdb-kv-store", default-features = false, features = [] }
proto-kv = { version = "0.1", path = "../proto-kv", package = "ofdb-kv-proto", default-features = false, features = [] }


# External dependencies
tokio = { version = "1.0", default-features = false, features = ["net", "rt", "macros"] }
tokio-stream = { version = "0.1", default-features = false, features = ["net"] }
tonic = { version = "0.14", default-features = false, features = ["transport", "server", "router", "codegen"] }

[dev-dependencies]
# Internal dependencies
kv-client = { version = "0.1", path = "../kv-client", package = "ofdb-kv-client", default-features = false, features = [] }

# External dependencies
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread", "macros", "sync", "time"] }

[features]
default = []
unix = []
