[package]
name = "ofdb-sql-client"
description = "gRPC client for ofdb SQL services"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# Internal dependencies

proto = { version = "0.1", path = "../sql-proto", package = "ofdb-sql-proto", default-features = false, features = [] }
protocol = { version = "0.1", path = "../sql-protocol", package = "ofdb-sql-protocol", default-features = false, features = [] }
query = { version = "0.1", path = "../sql-query", package = "ofdb-sql-query", default-features = false, features = [] }

# External dependencies
hyper-util = { version = "0.1", default-features = false, features = ["tokio"] }
tokio = { version = "1.0", default-features = false, features = ["net", "sync"] }
tokio-stream = { version = "0.1", default-features = false, features = [] }
tonic = { version = "0.14", default-features = false, features = ["transport", "channel", "codegen", "tls-ring"] }
tower = { version = "0.5", default-features = false, features = ["util"] }

[features]
default = []
unix = []
