[package]
name = "ofdb-sql-schema"
description = "db schema"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
name = "schema"

[features]
default = ["std"]
std = [
    "serde/std",

  "value/std"
]
wasm = ["dep:tsify", "dep:serde-wasm-bindgen", "dep:wasm-bindgen"]

[dependencies]
# internal dependencies
value = { version = "0.1", path = "../sql-value", package = "ofdb-sql-value", default-features = false, features = [] }

serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }

# Optional TS generation + serde for tsify
tsify = { version = "0.5", default-features = false, features = ["js"], optional = true }
serde-wasm-bindgen = { version = "0.6", default-features = false, features=[], optional = true }
wasm-bindgen = { version = "0.2", default-features = false, features = [
], optional = true }
