[package]
name = "ofdb-btree-automerge"
description = "Automerge storage adapter for ofdb-btree"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
name = "btree_automerge"

[features]
wasm = ["automerge/wasm"]
default = []

[dependencies]
# internal dependencies
btree = { version = "0.1", path = "../btree", package = "ofdb-btree", default-features = false, features = ["std"] }

async-stream = { version = "0.3", default-features = false, features = [] }
futures = { version = "0.3", default-features = false, features = [
  "std",
  "executor",
] }
uuid = { version = "1.4", default-features = false, features = ["v5", "v7", "serde", "std"] }
sha2 = { version = "0.10", default-features = false, features = ["std"] }
automerge = { version = "0.9", default-features = false, features = [] }
async-lock = { version = "3.4", default-features = false, features = ["std"] }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
base64 = { version = "0.21", default-features = false, features = ["std"] }

[dev-dependencies]
btree = { version = "0.1", path = "../btree", package = "ofdb-btree", default-features = false, features = [
  "in-memory",
  "std",
] }
