[package]
name = "protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# Internal dependencies
proto = { path = "../proto", default-features = false, features = [] }
value = { path = "../value", default-features = false, features = [] }
query = { path = "../query", default-features = false, features = [] }
schema = { path = "../schema", default-features = false, features = [] }

# External dependencies
uuid = { version = "1.0", default-features = false, features = [] }

[features]
default = []
