[package]
name = "ofdb-btree"
description = "Async BTree types and helpers"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
name = "btree"

[features]
default = ["std"]
std = [
  "futures/std",
  "async-lock?/std",
  "thiserror/std"
]
in-memory = ["dep:async-stream", "dep:async-lock"]

[dependencies]
async-lock = { version = "3.4", default-features = false, features = [], optional = true }
async-stream = { version = "0.3", default-features = false, features = [
], optional = true }
futures = { version = "0.3", default-features = false, features = [] }
thiserror = { version = "2.0", default-features = false, features = [] }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["executor"] }
