[package]
name = "ofdb-kv-sync"
description = "Explicit sync sessions for ofdb KV stores"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# Internal dependencies
btree = { version = "0.1", path = "../btree", package = "ofdb-btree", default-features = false, features = ["in-memory", "std"] }
btree-automerge = { version = "0.1", path = "../btree-automerge", package = "ofdb-btree-automerge", default-features = false, features = [] }

kv = { version = "0.1", path = "../kv-store", package = "ofdb-kv-store", default-features = false, features = [] }

# External dependencies
postcard = { version = "1.1", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["executor", "async-await", "std"] }
futures-channel = { version = "0.3", default-features = false, features = ["sink"] }
btree-redb = { version = "0.1", path = "../btree-redb", package = "ofdb-btree-redb", default-features = false, features = [] }
redb = { version = "4.3", default-features = false, features = ["uuid"] }
uuid = { version = "1.23", default-features = false, features = ["v7"] }
